### ISSUE TITLE
android firefox beta and firefox

### ISSUE THREAD

**Issue by duperray** [mozilla-services/syncserver#122]
On firefox {Beta,} 4 android, I get this stack trace (I run my own 1.5 sync server, which sync prefectly well with a debian firefox 52 desktop):

05-26 09:53:10.418 14629 14774 E FxAccounts: firefox_beta :: FxAccountSyncAdapter :: Got exception syncing.
05-26 09:53:10.418 14629 14774 E FxAccounts: org.mozilla.gecko.tokenserver.TokenServerException$TokenServerInvalidCredentialsException: {"status":"invalid-client-state","errors":[{"name":"X-Client-State","location":"header","description":"Unacceptable client-state value new value with no generation change"}]}
05-26 09:53:10.418 14629 14774 E FxAccounts:    at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:183)
05-26 09:53:10.418 14629 14774 E FxAccounts:    at org.mozilla.gecko.tokenserver.TokenServerClient$TokenFetchResourceDelegate.handleHttpResponse(TokenServerClient.java:281)

could it be related to android? Specific configuration of sync server for android?

regards,

Pierre

**Comment by rfk** [comment]
> "Unacceptable client-state value new value with no generation change"

I have a very vague recollection of seeing this error before, but I don't recall exactly where or why.  I think it might have been caused when upgrading the syncserver install past a certain version.  @duperray did you recently make any changes to your syncserver setup, such as config changes or updating to the latest version?

**Comment by duperray** [comment]
Yep, exactly,


I updated to lastest master, because I had another problem (I can't
remember the error, but found a thread tellin I had to upgrade to get rid

of this error).

**Comment by rfk** [comment]
OK, thanks.  I don't recall exactly what causes this error, but you should be able to "reset" the database state to get around it by doing something like:

* `DELETE FROM users WHERE replaced_at IS NOT NULL;`
* `UPDATE users SET generation = 0;`

**Comment by duperray** [comment]
Thanks so much Ryan,


Everything is in order now, it's perfect!

If I can help for further testing about this "database corruption" just
tell me.

Regards,


Pierre

**Comment by thomcc** [comment]
Someone reported this in IRC as well, is there a migration that should be happening that isn't? (Or is this just a case we know we don't handle / don't really care about)

**Comment by rfk** [comment]
I *think* this is to do with changing the underlying browserid verifier implementation, discussed a little in https://github.com/mozilla-services/syncserver/issues/91.  I haven't prioritized the work of trying to reproduce and figure out if it's possible to automatically recover from this situation.

**Comment by dagelf** [comment]
How did you get the initial log? (Latest Android Firefox is not syncing with latest syncserver for me... and I don't want to spend another hour or two digging into the code if not necessary. Thanks)

**Comment by rfk** [comment]
For getting logs off android, you need to use the [adb](https://developer.android.com/studio/command-line/adb) tool, specifically with its [logcat command](https://developer.android.com/studio/command-line/logcat).  We used to have a bit of [a write-up on how to do this specifically for sync](http://160.twinql.com/how-to-file-a-good-android-sync-bug) but unfortunately it appears to be a dead link these days :-(

**Comment by rfk** [comment]
I was reminded that the wayback machine is a thing, and has an archived copy of the "how to file a good android sync bug" page:

  https://web.archive.org/web/20160315032310/https://160.twinql.com/how-to-file-a-good-android-sync-bug/
