### ISSUE TITLE
Python-Error: No module named LocalBrowserIdVerifier

### ISSUE THREAD

**Issue by oschade** [mozilla-services/syncserver#144]
Hello,

I installed the syncserver on a raspberry pi. When I run it with `pserve /opt/syncserver/syncserver.ini` I get the following error

```
Traceback (most recent call last):
  File "/usr/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.5', 'console_scripts', 'pserve')()
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 51, in main
    return command.run()
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 316, in run
    global_conf=vars)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 340, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/opt/syncserver/syncserver/__init__.py", line 257, in main
    config = get_configurator(global_config, **settings)
  File "/opt/syncserver/syncserver/__init__.py", line 249, in get_configurator
    config.include(includeme)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    c(configurator)
  File "/opt/syncserver/syncserver/__init__.py", line 146, in includeme
    config.include("tokenserver", route_prefix="/token")
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    c(configurator)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/tokenserver/__init__.py", line 41, in includeme
    load_and_register("browserid", config)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/mozsvc/plugin.py", line 85, in load_and_register
    plugin = load_from_settings(section_name, settings)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/mozsvc/plugin.py", line 131, in load_from_settings
    klass = resolve_name(kwargs.pop("backend"))
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/mozsvc/util.py", line 54, in resolve_name
    return DottedNameResolver(package).resolve(name)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/path.py", line 300, in resolve
    return self._resolve(dotted, package)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/opt/syncserver/local/local/lib/python2.7/site-packages/pyramid/path.py", line 376, in _zope_dottedname_style
    __import__(used)
ImportError: No module named LocalBrowserIdVerifier

```

"make build" runs without an error.

**Comment by rfk** [comment]
`make build` will install all the dependencies into a local virtualenv in `./local/`, so you may need to run the python that's part of that virtualenv.  Does it work if you do `/opt/syncserver/local/bin/pserve /opt/syncserver/syncserver.ini` rather than using the system-level `pserve` executable?

**Comment by oschade** [comment]
Yeah, you right! Now it works! Thank you!
