### ISSUE TITLE
Error, Got token response: 404

### ISSUE THREAD

**Issue by ABeltramo** [mozilla-services/syncserver#152]
Hi there, I need help trubleshooting this.
I installed syncserver using Docker and the following docker-compose.yml

```yaml
  firefox-sync:
    image: mozilla/syncserver:latest
    volumes:
      - firefox-sync:/data
    restart: always
    depends_on: 
      - db
    environment:
      - SYNCSERVER_PUBLIC_URL=https://firefox.abeltra.me
      - SYNCSERVER_SQLURI=pymysql://<redacted>@db/ffsync
      - SYNCSERVER_SECRET=<redacted>
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
```

The server seems to be online and responding to requests from browser. If I try to start sync from Firefox on desktop this is the log:

 ```
1541939829586	Sync.LogManager	DEBUG	Flushing file log
1541939829587	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1541939829587	FirefoxAccounts	DEBUG	getOAuthToken enter
1541939829588	FirefoxAccounts	TRACE	getCachedToken returning cached token
1541939829588	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1541939829589	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1541939829589	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1541939829589	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1541939829589	Services.Common.RESTRequest	TRACE	HTTP Header if-none-match: "63be83fdcf8c2c5898ae340bd2c9aa52a51cb626-gzip"
1541939829597	Sync.LogManager	DEBUG	Log cleanup threshold time: 1541075829597
1541939829627	Sync.LogManager	DEBUG	Done deleting files.
1541939830251	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1541939830252	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 0
1541939830252	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1541940074807	Sync.Service	DEBUG	User-Agent: Firefox/63.0.1 (Intel Mac OS X 10.14) FxSync/1.65.0.20181030165643.desktop
1541940074807	Sync.Service	INFO	Starting sync at 2018-11-11 12:41:14 in browser session oU7kI3t6n09u
1541940074807	Sync.Service	DEBUG	In sync: should login.
1541940074807	Sync.Service	INFO	User logged in successfully - verifying login.
1541940074808	Sync.BrowserIDManager	DEBUG	unlockAndVerifyAuthState already has (or can fetch) sync keys
1541940074808	Sync.Status	DEBUG	Status.login: error.login.reason.network => success.status_ok
1541940074808	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1541940074809	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1541940074809	Sync.BrowserIDManager	INFO	Getting keys
1541940074809	Sync.BrowserIDManager	INFO	Getting an assertion from: https://firefox.abeltra.me/1.0/sync/1.5
1541940074809	FirefoxAccounts	DEBUG	enter getAssertion()
1541940074810	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1541940074810	FirefoxAccounts	DEBUG	getAssertionFromCert
1541940074813	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1541940074813	Sync.BrowserIDManager	DEBUG	Getting a token
1541940074814	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://firefox.abeltra.me/1.0/sync/1.5
1541940074814	Services.Common.RESTRequest	DEBUG	GET request to https://firefox.abeltra.me/1.0/sync/1.5
1541940074814	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1541940074814	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1541940074814	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1541940074841	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://firefox.abeltra.me/1.0/sync/1.5
1541940074841	Services.Common.RESTRequest	TRACE	Channel for GET https://firefox.abeltra.me/1.0/sync/1.5 returned status code 0
1541940074842	Services.Common.RESTRequest	DEBUG	GET https://firefox.abeltra.me/1.0/sync/1.5 404
1541940074842	Services.Common.TokenServerClient	DEBUG	Got token response: 404
1541940074842	Services.Common.RESTResponse	TRACE	Processing response headers.
1541940074842	Services.Common.TokenServerClient	WARN	Error processing token server response: TypeError: right-hand side of 'in' should be an object, got number(resource://services-common/tokenserverclient.js:303:7) JS Stack trace: _processTokenResponse@tokenserverclient.js:303:7
getTokenFromBrowserIDAssertion@tokenserverclient.js:249:14
1541940074842	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientError({"message":{}})(resource://services-common/tokenserverclient.js:36:36) JS Stack trace: TokenServerClientError@tokenserverclient.js:34:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:255:19
1541940074843	Sync.Status	DEBUG	Status.login: success.status_ok => error.login.reason.network
1541940074843	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1541940074843	Sync.BrowserIDManager	INFO	Failed to fetch the cluster URL: TokenServerClientError({"message":{}})(resource://services-common/tokenserverclient.js:36:36) JS Stack trace: TokenServerClientError@tokenserverclient.js:34:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:255:19
1541940074843	Sync.Service	DEBUG	verifyLogin failed: TokenServerClientError({"message":{}})(resource://services-common/tokenserverclient.js:36:36) JS Stack trace: TokenServerClientError@tokenserverclient.js:34:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:255:19
1541940074843	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1541940074843	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1541940074843	Sync.ErrorHandler	ERROR	Sync encountered a login error
1541940074844	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1541940074844	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1541940074845	Sync.Service	DEBUG	Exception calling WrappedLock: Error: Login failed: error.login.reason.network(resource://services-sync/service.js:872:15) JS Stack trace: onNotify@service.js:872:15
1541940074846	Sync.Service	DEBUG	Not syncing: login returned false.
```

I deployed it behind Caddy (similar to nginx) using the following settings: 
```
firefox.abeltra.me:443 {
	proxy / http://firefox-sync:5000 {
		transparent
	}
}
```

I tried many different settings, removing caddy and connecting directly to port 5000 seems to not change the error or the behaviour.
Running the suggested test suite will bring the following error:
```
python -m syncstorage.tests.functional.test_storage \
    --use-token-server https://firefox.abeltra.me/1.0/sync/1.5/
/Users/ale/.pyenv/versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
Traceback (most recent call last):
  File "/Users/ale/.pyenv/versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/ale/.pyenv/versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/ale/.pyenv/versions/2.7/lib/python2.7/site-packages/syncstorage/tests/functional/test_storage.py", line 2281, in <module>
    res = run_live_functional_tests(TestStorage, sys.argv)
  File "/Users/ale/.pyenv/versions/2.7/lib/python2.7/site-packages/syncstorage/tests/functional/support.py", line 203, in run_live_functional_tests
    creds = authenticate_to_token_server(url, opts.email, opts.audience)
  File "/Users/ale/.pyenv/versions/2.7/lib/python2.7/site-packages/syncstorage/tests/functional/support.py", line 135, in authenticate_to_token_server
    r.raise_for_status()
  File "/Users/ale/.pyenv/versions/2.7/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://firefox.abeltra.me/1.0/sync/1.5/
```

**Comment by ABeltramo** [comment]
Adding `/token/1.0/sync/1.5` to the docker-compose.yaml change the behaviour and the errors but it's still not completing succesfully.

```
1541942170050	Sync.Service	INFO	Loading Weave 1.65.0
1541942170052	Sync.Engine.Clients	DEBUG	Engine constructed
1541942170053	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1541942170061	Sync.Engine.Addons	DEBUG	Engine constructed
1541942170065	Sync.Engine.Addons	DEBUG	SyncEngine initialized: addons
1541942170068	Sync.Engine.Forms	DEBUG	Engine constructed
1541942170069	Sync.Engine.Forms	DEBUG	SyncEngine initialized: forms
1541942170071	Sync.Engine.History	DEBUG	Engine constructed
1541942170076	Sync.Engine.History	DEBUG	SyncEngine initialized: history
1541942170080	Sync.Engine.Passwords	DEBUG	Engine constructed
1541942170083	Sync.Engine.Passwords	DEBUG	SyncEngine initialized: passwords
1541942170085	Sync.Engine.Prefs	DEBUG	Engine constructed
1541942170086	Sync.Engine.Prefs	DEBUG	SyncEngine initialized: prefs
1541942170088	Sync.Engine.Tabs	DEBUG	Engine constructed
1541942170096	Sync.Engine.Tabs	DEBUG	SyncEngine initialized: tabs
1541942170096	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1541942170097	Sync.Engine.Extension-Storage	DEBUG	Engine constructed
1541942170099	Sync.Engine.Extension-Storage	DEBUG	SyncEngine initialized: extension-storage
1541942170101	Sync.Engine.Bookmarks	DEBUG	Engine constructed
1541942170102	Sync.Engine.Bookmarks	DEBUG	SyncEngine initialized: bookmarks
1541942170103	Sync.Service	INFO	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:63.0) Gecko/20100101 Firefox/63.0
1541942170104	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1541942170104	Sync.AddonsReconciler	DEBUG	Adding change listener.
1541942170104	Sync.Engine.History.Tracker	INFO	Adding Places observer.
1541942170109	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1541942170642	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1541942175112	Sync.SyncScheduler	DEBUG	Next sync in 3594888 ms. (why=startup)
1541942204583	Sync.RemoteTabs	INFO	Generating tab list with filter
1541942204583	Sync.RemoteTabs	INFO	Final tab list has 0 clients with 0 tabs.
1541942219733	Sync.Service	DEBUG	User-Agent: Firefox/63.0.1 (Intel Mac OS X 10.14) FxSync/1.65.0.20181030165643.desktop
1541942219733	Sync.Service	INFO	Starting sync at 2018-11-11 13:16:59 in browser session owgHOz3SIwPU
1541942219733	Sync.Service	DEBUG	In sync: should login.
1541942219733	Sync.Service	INFO	User logged in successfully - verifying login.
1541942219734	Sync.BrowserIDManager	DEBUG	unlockAndVerifyAuthState already has (or can fetch) sync keys
1541942219734	Sync.Status	DEBUG	Status.login: success.login => success.status_ok
1541942219734	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1541942219734	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1541942219734	Sync.BrowserIDManager	INFO	Getting keys
1541942219735	Sync.BrowserIDManager	INFO	Getting an assertion from: https://firefox.abeltra.me/1.0/sync/1.5
1541942219735	FirefoxAccounts	DEBUG	enter getAssertion()
1541942219740	FirefoxAccounts	DEBUG	got keyPair
1541942219740	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1541942219741	Services.Common.RESTRequest	TRACE	local time, offset: 1541942219741, 0
1541942219742	Services.Common.RESTRequest	DEBUG	POST request to https://api.accounts.firefox.com/v1/certificate/sign
1541942219742	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1541942219742	Services.Common.RESTRequest	TRACE	HTTP Header content-type: application/json
1541942219742	Services.Common.RESTRequest	TRACE	HTTP Header accept-language: it-IT, it, en-US, en
1541942219742	Services.Common.RESTRequest	DEBUG	POST Length: 888
1541942219742	Services.Common.RESTRequest	TRACE	POST Body: {"publicKey":{"algorithm":"DS","y":"B3F5217193A3C4DE0ED5E04C6E0AD3EA05A133D99C588C171772D99BF5B6D111158A6043A5144AFC49BB2178DB325A1F49900C6B4389F560DEC93DE815BDAE346E1F53BBC63BFD077E1D5C1C8B711F10926F0117BEF07FC49247B0B1716B65ACCE8ED3F4DB84C4E37FDF044A2FDE75D57B9FC34913042967EA2579085AAC85AE","p":"FF600483DB6ABFC5B45EAB78594B3533D550D9F1BF2A992A7A8DAA6DC34F8045AD4E6E0C429D334EEEAAEFD7E23D4810BE00E4CC1492CBA325BA81FF2D5A5B305A8D17EB3BF4A06A349D392E00D329744A5179380344E82A18C47933438F891E22AEEF812D69C8F75E326CB70EA000C3F776DFDBD604638C2EF717FC26D02E17","q":"E21E04F911D1ED7991008ECAAB3BF775984309C3","g":"C52A4A0FF3B7E61FDF1867CE84138369A6154F4AFA92966E3C827E25CFA6CF508B90E5DE419E1337E07A2E9E2A3CD5DEA704D175F8EBF6AF397D69E110B96AFB17C7A03259329E4829B0D03BBC7896B15B4ADE53E130858CC34D96269AA89041F409136C7242A38895C9D5BCCAD4F389AF1D7A4BD1398BD072DFFA896233397A"},"duration":21600000}
1541942220322	Services.Common.RESTRequest	TRACE	onStartRequest: POST https://api.accounts.firefox.com/v1/certificate/sign
1541942220322	Services.Common.RESTRequest	TRACE	Channel for POST https://api.accounts.firefox.com/v1/certificate/sign returned status code 0
1541942220322	Services.Common.RESTRequest	DEBUG	POST https://api.accounts.firefox.com/v1/certificate/sign 200
1541942220323	Hawk	DEBUG	(Response) /certificate/sign: code: 200 - Status text: OK
1541942220323	Services.Common.RESTResponse	TRACE	Processing response headers.
1541942220323	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -323
1541942220323	FirefoxAccounts	DEBUG	getCertificate got a new one: true
1541942220323	FirefoxAccounts	DEBUG	_updateAccountData with items: ["keyPair","cert"]
1541942220323	FirefoxAccounts	DEBUG	writing plain storage: ["email","sessionToken","uid","verified","device","oauthTokens","profileCache"]
1541942220323	FirefoxAccounts	TRACE	starting write of json user data: ["email","sessionToken","uid","verified","device","oauthTokens","profileCache"]
1541942220324	FirefoxAccounts	DEBUG	getAssertionFromCert
1541942220325	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1541942220325	Sync.BrowserIDManager	DEBUG	Getting a token
1541942220326	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://firefox.abeltra.me/1.0/sync/1.5
1541942220326	Services.Common.RESTRequest	DEBUG	GET request to https://firefox.abeltra.me/1.0/sync/1.5
1541942220326	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1541942220326	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1541942220326	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1541942220328	FirefoxAccounts	TRACE	finished write of json user data - took: 5
1541942220328	FirefoxAccounts	DEBUG	writing secure storage: ["kSync","kXCS","kExtSync","kExtKbHash"]
1541942220329	FirefoxAccounts	TRACE	starting write of user data to the login manager
1541942220334	FirefoxAccounts	TRACE	finished write of user data to the login manager
1541942220342	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://firefox.abeltra.me/1.0/sync/1.5
1541942220342	Services.Common.RESTRequest	TRACE	Channel for GET https://firefox.abeltra.me/1.0/sync/1.5 returned status code 0
1541942220342	Services.Common.RESTRequest	DEBUG	GET https://firefox.abeltra.me/1.0/sync/1.5 404
1541942220342	Services.Common.TokenServerClient	DEBUG	Got token response: 404
1541942220342	Services.Common.RESTResponse	TRACE	Processing response headers.
1541942220342	Services.Common.TokenServerClient	WARN	Error processing token server response: TypeError: right-hand side of 'in' should be an object, got number(resource://services-common/tokenserverclient.js:303:7) JS Stack trace: _processTokenResponse@tokenserverclient.js:303:7
getTokenFromBrowserIDAssertion@tokenserverclient.js:249:14
1541942220343	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientError({"message":{}})(resource://services-common/tokenserverclient.js:36:36) JS Stack trace: TokenServerClientError@tokenserverclient.js:34:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:255:19
1541942220343	Sync.Status	DEBUG	Status.login: success.status_ok => error.login.reason.network
1541942220343	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1541942220343	Sync.BrowserIDManager	INFO	Failed to fetch the cluster URL: TokenServerClientError({"message":{}})(resource://services-common/tokenserverclient.js:36:36) JS Stack trace: TokenServerClientError@tokenserverclient.js:34:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:255:19
1541942220343	Sync.Service	DEBUG	verifyLogin failed: TokenServerClientError({"message":{}})(resource://services-common/tokenserverclient.js:36:36) JS Stack trace: TokenServerClientError@tokenserverclient.js:34:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:255:19
1541942220343	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1541942220343	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1541942220344	Sync.ErrorHandler	ERROR	Sync encountered a login error
1541942220344	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1541942220345	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1541942220346	Sync.Service	DEBUG	Exception calling WrappedLock: Error: Login failed: error.login.reason.network(resource://services-sync/service.js:872:15) JS Stack trace: onNotify@service.js:872:15
1541942220346	Sync.Service	DEBUG	Not syncing: login returned false.
1541942220347	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
```

Is still getting token response: 404

**Comment by rfk** [comment]
> Adding `/token/1.0/sync/1.5` to the docker-compose.yaml

This needs to go in the `about:config` pref that you set in Firefox, but not in the server-side configuration.  IIUC from the logs, the following should work:

* For the server: `SYNCSERVER_PUBLIC_URL=https://firefox.abeltra.me`
* For Firefox: `identity.sync.tokenserver.uri=https://firefox.abeltra.me/token/1.0/sync/1.5`

**Comment by ABeltramo** [comment]
Thank you for the fast response. Unfortunately even using your settings is not working. Here is the log from `about:sync-log`.

```
1542012774437	Sync.Service	INFO	Loading Weave 1.65.0
1542012774438	Sync.Engine.Clients	DEBUG	Engine constructed
1542012774438	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1542012774438	Sync.Service	DEBUG	User-Agent: Firefox/63.0.1 (Intel Mac OS X 10.13) FxSync/1.65.0.20181030165643.desktop
1542012774441	Sync.Engine.Addons	DEBUG	Engine constructed
1542012774444	Sync.Engine.Addons	DEBUG	SyncEngine initialized: addons
1542012774445	Sync.Engine.Forms	DEBUG	Engine constructed
1542012774446	Sync.Engine.Forms	DEBUG	SyncEngine initialized: forms
1542012774447	Sync.Engine.History	DEBUG	Engine constructed
1542012774448	Sync.Engine.History	DEBUG	SyncEngine initialized: history
1542012774449	Sync.Engine.Passwords	DEBUG	Engine constructed
1542012774450	Sync.Engine.Passwords	DEBUG	SyncEngine initialized: passwords
1542012774450	Sync.Engine.Prefs	DEBUG	Engine constructed
1542012774451	Sync.Engine.Prefs	DEBUG	SyncEngine initialized: prefs
1542012774452	Sync.Engine.Tabs	DEBUG	Engine constructed
1542012774452	Sync.Engine.Tabs	DEBUG	SyncEngine initialized: tabs
1542012774452	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1542012774453	Sync.Engine.Extension-Storage	DEBUG	Engine constructed
1542012774453	Sync.Engine.Extension-Storage	DEBUG	SyncEngine initialized: extension-storage
1542012774455	Sync.Engine.Bookmarks	DEBUG	Engine constructed
1542012774458	Sync.Engine.Bookmarks	DEBUG	SyncEngine initialized: bookmarks
1542012774458	Sync.Service	INFO	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0
1542012774459	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1542012774459	Sync.AddonsReconciler	DEBUG	Adding change listener.
1542012774459	Sync.Engine.History.Tracker	INFO	Adding Places observer.
1542012774459	Sync.Service	INFO	Starting sync at 2018-11-12 08:52:54 in browser session 6PngNsUIBCSk
1542012774459	Sync.Service	DEBUG	In sync: should login.
1542012774459	Sync.Service	INFO	User logged in successfully - verifying login.
1542012774460	Sync.BrowserIDManager	DEBUG	unlockAndVerifyAuthState already has (or can fetch) sync keys
1542012774460	Sync.Status	DEBUG	Status.login: success.login => success.status_ok
1542012774460	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1542012774460	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1542012774460	Sync.BrowserIDManager	INFO	Getting keys
1542012774460	Sync.BrowserIDManager	INFO	Getting an assertion from: https://firefox.abeltra.me/token/1.0/sync/1.5
1542012774460	FirefoxAccounts	DEBUG	enter getAssertion()
1542012774462	Sync.Status	DEBUG	Status.service: error.login.failed => success.status_ok
1542012774462	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1542012774463	FirefoxAccounts	DEBUG	got keyPair
1542012774463	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1542012774464	Services.Common.RESTRequest	TRACE	local time, offset: 1542012774464, 0
1542012774464	Services.Common.RESTRequest	DEBUG	POST request to https://api.accounts.firefox.com/v1/certificate/sign
1542012774464	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1542012774464	Services.Common.RESTRequest	TRACE	HTTP Header content-type: application/json
1542012774464	Services.Common.RESTRequest	TRACE	HTTP Header accept-language: en-GB, en
1542012774465	Services.Common.RESTRequest	DEBUG	POST Length: 888
1542012774465	Services.Common.RESTRequest	TRACE	POST Body: {"publicKey":{"algorithm":"DS","y":"93C3237D6E7CD6AB6ADB6EF0B18C0C8CC2A706D38DF6ED9A86A1DE4CA8C2343C225EFB95C70BB9924E25E80A52A923464B2A35D8EA9487558658223D533DF4BB76E76F4D678ADA06B864BD2BAA0E611FBA8CE95C0EB2C31191B6D72E49780FE96CFC80A2969881A8F799D9BD786E391BEEEB784D681A1C54D2AA797FF81029A0","p":"FF600483DB6ABFC5B45EAB78594B3533D550D9F1BF2A992A7A8DAA6DC34F8045AD4E6E0C429D334EEEAAEFD7E23D4810BE00E4CC1492CBA325BA81FF2D5A5B305A8D17EB3BF4A06A349D392E00D329744A5179380344E82A18C47933438F891E22AEEF812D69C8F75E326CB70EA000C3F776DFDBD604638C2EF717FC26D02E17","q":"E21E04F911D1ED7991008ECAAB3BF775984309C3","g":"C52A4A0FF3B7E61FDF1867CE84138369A6154F4AFA92966E3C827E25CFA6CF508B90E5DE419E1337E07A2E9E2A3CD5DEA704D175F8EBF6AF397D69E110B96AFB17C7A03259329E4829B0D03BBC7896B15B4ADE53E130858CC34D96269AA89041F409136C7242A38895C9D5BCCAD4F389AF1D7A4BD1398BD072DFFA896233397A"},"duration":21600000}
1542012774927	Services.Common.RESTRequest	TRACE	onStartRequest: POST https://api.accounts.firefox.com/v1/certificate/sign
1542012774928	Services.Common.RESTRequest	TRACE	Channel for POST https://api.accounts.firefox.com/v1/certificate/sign returned status code 0
1542012774928	Services.Common.RESTRequest	DEBUG	POST https://api.accounts.firefox.com/v1/certificate/sign 200
1542012774928	Hawk	DEBUG	(Response) /certificate/sign: code: 200 - Status text: OK
1542012774928	Services.Common.RESTResponse	TRACE	Processing response headers.
1542012774928	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -928
1542012774929	FirefoxAccounts	DEBUG	getCertificate got a new one: true
1542012774929	FirefoxAccounts	DEBUG	_updateAccountData with items: ["keyPair","cert"]
1542012774929	FirefoxAccounts	DEBUG	writing plain storage: ["email","sessionToken","uid","verified","device","oauthTokens","profileCache"]
1542012774929	FirefoxAccounts	TRACE	starting write of json user data: ["email","sessionToken","uid","verified","device","oauthTokens","profileCache"]
1542012774929	FirefoxAccounts	DEBUG	getAssertionFromCert
1542012774931	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1542012774931	Sync.BrowserIDManager	DEBUG	Getting a token
1542012774931	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://firefox.abeltra.me/token/1.0/sync/1.5
1542012774931	Services.Common.RESTRequest	DEBUG	GET request to https://firefox.abeltra.me/token/1.0/sync/1.5
1542012774931	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1542012774931	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1542012774932	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1542012774932	FirefoxAccounts	TRACE	finished write of json user data - took: 3
1542012774932	FirefoxAccounts	DEBUG	writing secure storage: ["kSync","kXCS","kExtSync","kExtKbHash"]
1542012774932	FirefoxAccounts	TRACE	starting write of user data to the login manager
1542012774936	FirefoxAccounts	TRACE	finished write of user data to the login manager
1542012774984	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://firefox.abeltra.me/token/1.0/sync/1.5
1542012774984	Services.Common.RESTRequest	TRACE	Channel for GET https://firefox.abeltra.me/token/1.0/sync/1.5 returned status code 0
1542012774984	Services.Common.RESTRequest	DEBUG	GET https://firefox.abeltra.me/token/1.0/sync/1.5 200
1542012774985	Services.Common.TokenServerClient	DEBUG	Got token response: 200
1542012774985	Services.Common.RESTResponse	TRACE	Processing response headers.
1542012774985	Services.Common.TokenServerClient	DEBUG	Successful token response
1542012774985	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for undefined
1542012774985	Sync.Status	DEBUG	Status.login: success.status_ok => success.login
1542012774986	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542012774986	Sync.BrowserIDManager	DEBUG	_findCluster returning https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/
1542012774986	Sync.BrowserIDManager	DEBUG	Cluster value = https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/
1542012774986	Sync.BrowserIDManager	DEBUG	Setting cluster to https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/
1542012774986	Sync.Service	DEBUG	Caching URLs under storage user base: https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/
1542012774988	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1542012775000	Sync.Resource	DEBUG	GET fail 404 https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/info/collections
1542012775000	Sync.Resource	WARN	GET request to https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/info/collections failed with status 404
1542012775000	Sync.BrowserIDManager	DEBUG	_findCluster has a pre-existing clusterURL, so fetching a new token token
1542012775001	Sync.BrowserIDManager	INFO	Getting keys
1542012775001	Sync.BrowserIDManager	INFO	Getting an assertion from: https://firefox.abeltra.me/token/1.0/sync/1.5
1542012775001	FirefoxAccounts	DEBUG	enter getAssertion()
1542012775001	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1542012775001	FirefoxAccounts	DEBUG	getAssertionFromCert
1542012775002	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1542012775002	Sync.BrowserIDManager	DEBUG	Getting a token
1542012775002	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://firefox.abeltra.me/token/1.0/sync/1.5
1542012775003	Services.Common.RESTRequest	DEBUG	GET request to https://firefox.abeltra.me/token/1.0/sync/1.5
1542012775003	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1542012775003	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1542012775003	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1542012775021	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://firefox.abeltra.me/token/1.0/sync/1.5
1542012775021	Services.Common.RESTRequest	TRACE	Channel for GET https://firefox.abeltra.me/token/1.0/sync/1.5 returned status code 0
1542012775021	Services.Common.RESTRequest	DEBUG	GET https://firefox.abeltra.me/token/1.0/sync/1.5 200
1542012775021	Services.Common.TokenServerClient	DEBUG	Got token response: 200
1542012775021	Services.Common.RESTResponse	TRACE	Processing response headers.
1542012775022	Services.Common.TokenServerClient	DEBUG	Successful token response
1542012775022	Sync.Status	DEBUG	Status.login: success.login => success.login
1542012775022	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542012775022	Sync.BrowserIDManager	DEBUG	_findCluster returning https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/
1542012775022	Sync.BrowserIDManager	DEBUG	Cluster value = https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/
1542012775022	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1542012775022	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1542012775022	Sync.ErrorHandler	ERROR	Sync encountered a login error
1542012775022	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1542012775023	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1542012775023	Sync.Service	DEBUG	Exception calling WrappedLock: Error: Login failed: error.login.reason.network(resource://services-sync/service.js:872:15) JS Stack trace: onNotify@service.js:872:15
1542012775024	Sync.Service	DEBUG	Not syncing: login returned false.
1542012775024	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
```

**Comment by rfk** [comment]
The problem appears to be here, where the returned cluster URL is unexpectedly including the `/token` prefix:

> 1542012775022	Sync.BrowserIDManager	DEBUG	Cluster value = https://firefox.abeltra.me/token/1.0/sync/1.5/storage/1.5/1/

I would expect this URL to look like `https://firefox.abeltra.me/storage/1.5/1/`, so I suspect a config issue on the server is causing it to return the wrong value.  Do you have the `/token` prefix on *any* of the URLs in your server-side config?

**Comment by ABeltramo** [comment]
> 
> This needs to go in the `about:config` pref that you set in Firefox, but not in the server-side configuration. IIUC from the logs, the following should work:
> 
>     * For the server: `SYNCSERVER_PUBLIC_URL=https://firefox.abeltra.me`
> 
>     * For Firefox: `identity.sync.tokenserver.uri=https://firefox.abeltra.me/token/1.0/sync/1.5`

Thank you so much for the help. Double checking this settings have in fact corrected the issue for me.
