### ISSUE TITLE
Missing cloumns in database when upgrading from odler version 

### ISSUE THREAD

**Issue by StefanAbl** [mozilla-services/syncserver#208]
Hi,
when I upgraded my syncserver from an older version I received this error: 
```
[2020-03-24 15:49:31 +0000] [22189] [ERROR] Error handling request /token/1.0/sync/1.5
Traceback (most recent call last):
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/tokenserver/tweens.py", line 15, in set_x_timestamp_header_tween
    response = handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tweens.py", line 123, in convert_non_json_responses_tween
    response = handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tweens.py", line 99, in convert_cornice_errors_to_respcodes_tween
    response = handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tweens.py", line 53, in set_default_accept_header_tween
    return handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tweens.py", line 30, in set_x_timestamp_header_tween
    response = handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/mozsvc/tweens.py", line 94, in fuzz_backoff_headers_tween
    response = handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/mozsvc/tweens.py", line 59, in log_uncaught_exceptions_tween
    return handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/mozsvc/tweens.py", line 26, in catch_backend_errors_tween
    return handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/cornice/service.py", line 514, in wrapper
    response = view_(request)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/tokenserver/views.py", line 345, in return_token
    user = backend.get_user(service, email)
  File "/var/www/syncserver/syncserver/staticnode.py", line 135, in get_user
    res = self._engine.execute(_GET_USER_RECORDS, **params)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2166, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/syncserver/local/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (pymysql.err.InternalError) (1054, u"Unknown column 'keys_changed_at' in 'field list'")
[SQL: select
    uid, generation, client_state, created_at, replaced_at,
    keys_changed_at, node
from
    users
where
    email = %(email)s
and
    service = %(service)s
order by
    created_at desc, uid desc
limit
    20
]
[parameters: {'email': random_value@api.accounts.firefox.com', 'service': u'sync-1.5'}]
```

I was able to trace it back to the fact that the syncserver now requires two more columns in the users table. I was able to create these with the following mysql command:
```
ALTER TABLE users 
ADD COLUMN keys_changed_at BIGINT(20) AFTER replaced_at;
ALTER TABLE users
ADD COLUMN node VARCHAR(255) AFTER keys_changed_at;
```
After this it now seems to be working fine.

Maybe it would be possible to check if all columns exist and if not create the missing ones after an upgrade.

The syncserver is running on ubuntu 16 and the databse is MariaDB.

Thanks
Stefan

**Comment by cynicer** [comment]
Thanks for the quick fix. Should really be done on upgrade though.

For SQLite it is:
`ALTER TABLE users ADD COLUMN keys_changed_at BIGINT(20);
ALTER TABLE users ADD COLUMN node VARCHAR(255);`

Thanks,
Marcel
