### ISSUE TITLE
Add support for arm docker

### ISSUE THREAD

**Issue by TrAnn3l** [mozilla-services/syncserver#219]
Would be great when i could run the docker image on my raspberry.

**Comment by FibreFoX** [comment]
At first I thought that building with a fresh checkout would work, but it seems that **it does not work**.

While building fresh I can see this errors:
```
Installing collected packages: repoze.lru, translationstring, PasteDeploy, zope.interface, zope.deprecation, venusian, WebOb, pyramid, simplejson, cornice, gunicorn, idna, urllib3, chardet, certifi, requests, SQLAlchemy, argparse, six, linecache2, traceback2, unittest2, zope.event, zope.component, configparser, konfig, mozsvc, futures, backports.functools-lru-cache, soupsieve, umemcache, protobuf, pytz, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, googleapis-common-protos, enum34, grpcio, grpcio-gcp, google-api-core, grpc-google-iam-v1, google-cloud-core, google-cloud-spanner, MarkupSafe, Mako, python-editor, python-dateutil, alembic, asn1crypto, boto, ipaddress, pycparser, cffi, cryptography, greenlet, gevent, hawkauthlib, hupper, mysqlclient, Paste, plaster, plaster-pastedeploy, PyBrowserID, PyJWT, PyFxA, PyMySQL, pymysql-sa, testfixtures, tokenlib, tokenserver, pyramid-hawkauth, wsgiproxy, beautifulsoup4, waitress, webtest, SyncStorage
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
requests 2.20.0 requires idna<2.8,>=2.5, but you'll have idna 2.8 which is incompatible.
requests 2.20.0 requires urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
gevent 1.4.0 requires greenlet>=0.4.14; platform_python_implementation == "CPython", but you'll have greenlet 0.4.13 which is incompatible.
tokenserver 1.5.11 requires configparser==3.7.4, but you'll have configparser 3.5.0 which is incompatible.
tokenserver 1.5.11 requires cornice==3.5.1, but you'll have cornice 0.16.2 which is incompatible.
tokenserver 1.5.11 requires gunicorn==19.10.0, but you'll have gunicorn 19.6.0 which is incompatible.
tokenserver 1.5.11 requires mozsvc==0.10, but you'll have mozsvc 0.9 which is incompatible.
tokenserver 1.5.11 requires pyramid==1.10.4, but you'll have pyramid 1.5.3 which is incompatible.
tokenserver 1.5.11 requires requests==2.22.0, but you'll have requests 2.20.0 which is incompatible.
tokenserver 1.5.11 requires WebOb==1.8.5, but you'll have webob 1.4.1 which is incompatible.
google-api-core 1.24.1 requires futures>=3.2.0; python_version < "3.2", but you'll have futures 3.0.0 which is incompatible.
Successfully installed Mako-1.0.9 MarkupSafe-1.1.1 Paste-3.0.8 PasteDeploy-2.0.1 PyBrowserID-0.14.0 PyFxA-0.7.7 PyJWT-1.7.1 PyMySQL-0.9.3 SQLAlchemy-1.3.3 SyncStorage-1.8.0 WebOb-1.4.1 alembic-1.0.9 argparse-1.4.0 asn1crypto-0.24.0 backports.functools-lru-cache-1.6.1 beautifulsoup4-4.9.3 boto-2.49.0 cachetools-3.1.1 certifi-2019.3.9 cffi-1.14.0 chardet-3.0.4 configparser-3.5.0 cornice-0.16.2 cryptography-2.6.1 enum34-1.1.6 futures-3.0.0 gevent-1.4.0 google-api-core-1.24.1 google-auth-1.24.0 google-cloud-core-1.5.0 google-cloud-spanner-1.18.0 googleapis-common-protos-1.52.0 greenlet-0.4.13 grpc-google-iam-v1-0.12.3 grpcio-1.34.0 grpcio-gcp-0.2.2 gunicorn-19.6.0 hawkauthlib-2.0.0 hupper-1.6.1 idna-2.8 ipaddress-1.0.22 konfig-1.1 linecache2-1.0.0 mozsvc-0.9 mysqlclient-1.4.6 plaster-1.0 plaster-pastedeploy-0.7 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.19 pymysql-sa-1.0 pyramid-1.5.3 pyramid-hawkauth-2.0.0 python-dateutil-2.8.0 python-editor-1.0.4 pytz-2020.4 repoze.lru-0.7 requests-2.20.0 rsa-4.5 simplejson-3.16.0 six-1.14.0 soupsieve-1.9.5 testfixtures-6.7.0 tokenlib-2.0.0 tokenserver-1.5.11 traceback2-1.4.0 translationstring-1.3 umemcache-1.6.3 unittest2-1.1.0 urllib3-1.25.2 venusian-1.2.0 waitress-1.4.4 webtest-2.0.35 wsgiproxy-0.2.2 zope.component-4.2.1 zope.deprecation-4.4.0 zope.event-4.5.0 zope.interface-4.6.0
```

Even tho it seems to create an docker image, but when starting the server, I get strange errors:
```
syncserver    | [2020-12-17 11:00:36 +0000] [8] [INFO] Starting gunicorn 19.6.0
syncserver    | [2020-12-17 11:00:36 +0000] [8] [INFO] Listening at: http://0.0.0.0:4000 (8)
syncserver    | [2020-12-17 11:00:36 +0000] [8] [INFO] Using worker: sync
syncserver    | [2020-12-17 11:00:36 +0000] [16] [INFO] Booting worker with pid: 16
syncserver    | /usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
syncserver    |   RequestsDependencyWarning)
syncserver    | ERROR:syncstorage.storage:Error while scanning package 'syncstorage.storage.spanner'
syncserver    | Traceback (most recent call last):
syncserver    |   File "/usr/local/lib/python2.7/site-packages/venusian/__init__.py", line 230, in scan
syncserver    |     __import__(modname)
syncserver    |   File "/usr/local/lib/python2.7/site-packages/syncstorage/storage/spanner.py", line 20, in <module>
syncserver    |     from google.cloud import spanner
syncserver    |   File "/usr/local/lib/python2.7/site-packages/google/cloud/spanner.py", line 19, in <module>
syncserver    |     from google.cloud.spanner_v1 import __version__
syncserver    |   File "/usr/local/lib/python2.7/site-packages/google/cloud/spanner_v1/__init__.py", line 23, in <module>
syncserver    |     from google.cloud.spanner_v1.client import Client
syncserver    |   File "/usr/local/lib/python2.7/site-packages/google/cloud/spanner_v1/client.py", line 26, in <module>
syncserver    |     import grpc
syncserver    |   File "/usr/local/lib/python2.7/site-packages/grpc/__init__.py", line 23, in <module>
syncserver    |     from grpc._cython import cygrpc as _cygrpc
syncserver    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /usr/local/lib/python2.7/site-packages/grpc/_cython/cygrpc.so)
```

**Comment by zynaa** [comment]
I was able to get it running by reverting to commit e1aab54cbcb6e570979835789f7b4624eebdc875 (as described [here](https://github.com/mozilla-services/syncserver/issues/231#issuecomment-687882226)) and then building the image.
