### ISSUE TITLE
Dependency conflict between requests and google-api-core

### ISSUE THREAD

**Issue by DigNative** [mozilla-services/syncserver#250]
I am observing the following error of the Firefox Sync Server (bfbc3abd36ee4db70df13a9c43f7758a1528c965) on server side:

```
mod_wsgi (pid=31618): Target WSGI script '/srv/software/mozilla-syncserver/syncserver.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=31618): Exception occurred processing WSGI script '/srv/software/mozilla-syncserver/syncserver.wsgi'.
Traceback (most recent call last):
  File "/srv/software/mozilla-syncserver/syncserver.wsgi", line 43, in <module>
    application = loadapp('config:%s'% ini_file)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    ############################################################
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    self.loader = loader
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    if context.protocol in ('paste.composit_factory',
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/srv/software/mozilla-syncserver/syncserver/__init__.py", line 281, in main
    config = get_configurator(global_config, **settings)
  File "/srv/software/mozilla-syncserver/syncserver/__init__.py", line 273, in get_configurator
    config.include(includeme)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    configurator.includepath = self.includepath + (spec,)
  File "/srv/software/mozilla-syncserver/syncserver/__init__.py", line 158, in includeme
    config.include("syncstorage", route_prefix="/storage")
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    configurator.includepath = self.includepath + (spec,)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/syncstorage/__init__.py", line 18, in includeme
    config.include("syncstorage.storage")
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
    configurator.includepath = self.includepath + (spec,)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 565, in includeme
    # E.g: "host:localhost.storage.sqluri" => "localhost"
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 929, in scan
    scanner.scan(package, categories=categories, onerror=onerror,
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/venusian/__init__.py", line 233, in scan
    onerror(modname)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/syncstorage/storage/spanner.py", line 19, in <module>
    from google.api_core.exceptions import Aborted, AlreadyExists
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/google/api_core/__init__.py", line 23, in <module>
    __version__ = get_distribution("google-api-core").version
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in get_distribution
    entries = sys.path
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 436, in get_provider
    # setuptools 0.6. All packages built after this point will
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
    self.scan(search_path)
  File "/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 875, in resolve
    else:
ContextualVersionConflict: (requests 2.13.0 (/srv/software/mozilla-syncserver/local/lib/python2.7/site-packages), Requirement.parse('requests<3.0.0dev,>=2.18.0'), set(['google-api-core']))
```

On client side, the sync attempt fails:

```
1601109261130	Sync.Resource	WARN	Got exception parsing response body: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data(resource://services-sync/resource.js:229:21) JS Stack trace: _processResponse/<@resource.js:229:21
get@XPCOMUtils.jsm:58:51
format@Log.jsm:642:19
formatText@Log.jsm:571:44
format@Log.jsm:589:12
append@Log.jsm:682:37
append@logmanager.js:156:44
log@Log.jsm:379:16
error@Log.jsm:387:10
observe@policies.js:924:19
observe@observers.js:135:21
notify@observers.js:87:18
notify@util.js:204:19
WrappedNotify@util.js:214:17
1601109261130	Sync.Resource	DEBUG	Parse fail: Response body starts: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</ti
1601109261129	Sync.ErrorHandler	ERROR	Sync encountered an error: ({data:"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>500 Internal Server Error</title>\n</head><body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.</p>\n<p>Please contact the server administrator at \n REDACTED to inform them of the time this error occurred,\n and the actions you performed just before this error.</p>\n<p>More information about this error may be available\nin the server error log.</p>\n</body></html>\n", url:"https://REDACTED/storage/1.5/4/info/collections", status:500, success:false, headers:{connection:"close", 'content-length':"534", 'content-type':"text/html; charset=iso-8859-1", date:"Sat, 26 Sep 2020 08:34:22 GMT", server:"Apache", 'strict-transport-security':"max-age=15768000; includeSubdomains; preload"}, get obj() {
        if (!redefining) {
          // Make sure we don't get into an infinite recursion loop if
          // the getter lambda does something shady.
          redefining = true;
          return redefine(aObject, aName, aLambda.apply(aObject));
        }
      }})
```

**Comment by jrconlin** [comment]
Sadly, this is one of the problems of running in python2. While the Python image may persist for a while thanks to efforts like pypy, the libraries are more of a "moving target", and will require further lock down. I'll also add that a further complexity is that secondary dependencies (like OpenSSL or other libraries that the python libraries may require) are also changing and may lead to these sorts of conflicts. 

If you wish to run the existing python version, it may become increasingly necessary to run it either in a Docker image or a similar VM sort of setup. 

That said, we are also working on a more modern Rust implementation, and could use some help getting the [stand alone system](https://github.com/mozilla-services/syncstorage-rs/issues/550) smoothed out for folk.
