### ISSUE TITLE
Support for armhf

### ISSUE THREAD

**Issue by danielandross** [mozilla-services/syncserver#257]
Since there is no armv7 image on hub.docker I wanted to build myself. Building works fine (master). But when starting a container I get this:
`[2020-10-26 09:09:28 +0000] [14] [INFO] Booting worker with pid: 14
/usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
ERROR:syncstorage.storage:Error while scanning package 'syncstorage.storage.spanner'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/usr/local/lib/python2.7/site-packages/syncstorage/storage/spanner.py", line 20, in <module>
    from google.cloud import spanner
  File "/usr/local/lib/python2.7/site-packages/google/cloud/spanner.py", line 19, in <module>
    from google.cloud.spanner_v1 import __version__
  File "/usr/local/lib/python2.7/site-packages/google/cloud/spanner_v1/__init__.py", line 23, in <module>
    from google.cloud.spanner_v1.client import Client
  File "/usr/local/lib/python2.7/site-packages/google/cloud/spanner_v1/client.py", line 26, in <module>
    import grpc
  File "/usr/local/lib/python2.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: Error relocating /usr/local/lib/python2.7/site-packages/grpc/_cython/cygrpc.so: __strdup: symbol not found`

Do you plan on restoring arm support any time soon? Cheers.

**Comment by jrconlin** [comment]
ARM support is currently not a priority for our team. Please note that Python 2.7 has been deprecated and our team is currently working on a replacement version in Rust. 

Google Spanner is a cloud based storage system used by our production server, and is not required for MySQL support. It may be preferable to modify things to not include the `google-cloud-spanner` module. Some additional work may be required to exclude spanner from the `syncstorage` package.
