### ISSUE TITLE
"ConfigurationError: 'acl' is not supported" errors when running "make test"

### ISSUE THREAD

**Issue by CyberShadow** [mozilla-services/syncserver#278]
Running `make test` on Ubuntu bionic results in 69/72 failures.

The failures seem to all be due to exceptions such as:

```
======================================================================
ERROR: test_validation_of_user_data_from_token (syncstorage.tests.test_wsgiapp.TestWSGIApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tests/support.py", line 28, in wrapper
    return func(*args, **kwds)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tests/support.py", line 83, in setUp
    super(StorageTestCase, self).setUp()
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/mozsvc/tests/support.py", line 67, in setUp
    self.config = self.get_configurator()
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/syncstorage/tests/support.py", line 94, in get_configurator
    config.include("syncstorage")
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 676, in include
    c(configurator)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/syncstorage/__init__.py", line 19, in includeme
    config.include("syncstorage.views")
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 642, in include
    c = self.maybe_dotted(callable)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 749, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/pyramid/path.py", line 335, in maybe_resolve
    return self._resolve(dotted, package)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/pyramid/path.py", line 342, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/pyramid/path.py", line 397, in _zope_dottedname_style
    __import__(used)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/syncstorage/views/__init__.py", line 158, in <module>
    path="")
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/syncstorage/views/__init__.py", line 112, in __init__
    super(SyncStorageService, self).__init__(**kwds)
  File "/home/fxsync/syncserver/local/local/lib/python2.7/site-packages/cornice/service.py", line 196, in __init__
    raise ConfigurationError("'acl' is not supported")
ConfigurationError: 'acl' is not supported
```

The following patch (as suggested [here](https://aur.archlinux.org/packages/mozilla-firefox-sync-server/#comment-690663)) seems to resolve the issue:

```diff
diff --git a/requirements.txt b/requirements.txt
index b1d268c..991a24f 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,6 +1,6 @@
 gevent==1.4.0
 greenlet==0.4.14
-cornice==3.5.1
+cornice==0.16.2
 gunicorn==19.10.0
 pyramid==1.10.4
 WebOb==1.8.5
```

**Comment by CyberShadow** [comment]
Commit eb47d3577056248a0c8ebd1b7182ca6b39aa0ffa bumped `cornice` to `3.5.1`, an apparently incompatible version. CC @pmkohn

**Comment by misterhsp** [comment]
I can confirm that.

...
