### ISSUE TITLE
build error: mysql_config not found

### ISSUE THREAD

**Issue by AndiCorradi** [mozilla-services/syncserver#291]
while running make build , i get an error that mysql_config is not found.
Where i am supposed to configure the db-config ? I try to edit the syncserver.ini file but that does not help.

Collecting mysqlclient==1.4.6
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /syncserver/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ORSbZl/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ORSbZl/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5oPKfq
         cwd: /tmp/pip-install-ORSbZl/mysqlclient/
    Complete output (12 lines):
    sh: 1: mysql_config: not found
    sh: 1: mariadb_config: not found
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ORSbZl/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [Makefile:31: local/COMPLETE] Error 1

**Comment by AndiCorradi** [comment]
sudo apt-get install libmysqlclient-dev did the trick
