### ISSUE TITLE
Firefox Mobile Sync issues

### ISSUE THREAD

**Issue by canihavesomecoffee** [mozilla-services/syncserver#69]
Hello,

I'm currently running my own Sync Server instance for a couple of months now, and so far it's been great, running it on desktops & laptops. However, I'd like to use it on Android as well, but it seems right now that there's some error I can't fix myself...

Everything is set up correctly (given that I can sync from two other devices flawlessly), and seeing that there is an actual request to the server, it seems that the setup in firefox mobile should be correct too...

Every now and then, Firefox makes a background request to sync, and it always errors out on this one:
```
195.202.166.190 - - [19/Dec/2015:03:38:14 +0100] "GET /1.0/sync/1.5 HTTP/1.1" 404 1 "-" "Firefox-Android-FxAccounts/43.0 (Firefox)"
```

Using ADB I managed to obtain this log from Firefox:

```
D/FxAccounts(19418): firefox :: AndroidFxAccount :: Account is in state Married
I/FxAccounts(19418): firefox :: FxAccountNotificationManager :: State Married needs no action; cancelling any existing notification.
I/FxAccounts(19418): firefox :: LoginStateMachineDelegate :: handleMarried: in Married
D/FxAccounts(19418): firefox :: BaseResource :: HTTP GET https://sync.domain.tld/1.0/sync/1.5
D/FxAccounts(19418): firefox :: BaseResource :: Added auth header.
D/FxAccounts(19418): firefox :: BaseResource :: Response: HTTP/1.1 404 Not Found
D/FxAccounts(19418): firefox :: SkewHandler :: Updated skew: 792ms for hostname domain.tld
D/FxAccounts(19418): firefox :: TokenServerClient :: Got token response with status code 404.
D/FxAccounts(19418): firefox :: TokenServerClient :: Malformed token response.
D/FxAccounts(19418): org.mozilla.gecko.sync.NonObjectJSONException: value must be a JSON object
D/FxAccounts(19418):    at org.mozilla.gecko.sync.ExtendedJSONObject.<init>(ExtendedJSONObject.java:217)
D/FxAccounts(19418):    at org.mozilla.gecko.sync.net.MozResponse.jsonObjectBody(MozResponse.java:110)
D/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:152)
D/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient$TokenFetchResourceDelegate.handleHttpResponse(TokenServerClient.java:280)
D/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:309)
D/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:340)
D/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.get(BaseResource.java:346)
D/FxAccounts(19418):    at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter.syncWithAssertion$1a55e242(FxAccountSyncAdapter.java:373)
D/FxAccounts(19418):    at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter$3.handleMarried(FxAccountSyncAdapter.java:542)
D/FxAccounts(19418):    at org.mozilla.gecko.fxa.authenticator.FxADefaultLoginStateMachineDelegate.handleFinal(FxADefaultLoginStateMachineDelegate.java:81)
D/FxAccounts(19418):    at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine$ExecuteDelegate.handleTransition(FxAccountLoginStateMachine.java:64)
D/FxAccounts(19418):    at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:28)
D/FxAccounts(19418):    at org.mozilla.gecko.background.fxa.FxAccountClient10$10.handleSuccess$2637ceed(FxAccountClient10.java:770)
D/FxAccounts(19418):    at org.mozilla.gecko.background.fxa.FxAccountClient10$ResourceDelegate$2.run(FxAccountClient10.java:291)
D/FxAccounts(19418):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D/FxAccounts(19418):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D/FxAccounts(19418):    at java.lang.Thread.run(Thread.java:818)
E/FxAccounts(19418): firefox :: FxAccountSyncAdapter :: Failed to get token.
E/FxAccounts(19418): org.mozilla.gecko.tokenserver.TokenServerException$TokenServerMalformedResponseException: org.mozilla.gecko.sync.NonObjectJSONException: value must be a JSON object
E/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:155)
E/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient$TokenFetchResourceDelegate.handleHttpResponse(TokenServerClient.java:280)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:309)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:340)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.get(BaseResource.java:346)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter.syncWithAssertion$1a55e242(FxAccountSyncAdapter.java:373)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter$3.handleMarried(FxAccountSyncAdapter.java:542)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.authenticator.FxADefaultLoginStateMachineDelegate.handleFinal(FxADefaultLoginStateMachineDelegate.java:81)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine$ExecuteDelegate.handleTransition(FxAccountLoginStateMachine.java:64)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:28)
E/FxAccounts(19418):    at org.mozilla.gecko.background.fxa.FxAccountClient10$10.handleSuccess$2637ceed(FxAccountClient10.java:770)
E/FxAccounts(19418):    at org.mozilla.gecko.background.fxa.FxAccountClient10$ResourceDelegate$2.run(FxAccountClient10.java:291)
E/FxAccounts(19418):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/FxAccounts(19418):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/FxAccounts(19418):    at java.lang.Thread.run(Thread.java:818)
E/FxAccounts(19418): Caused by: org.mozilla.gecko.sync.NonObjectJSONException: value must be a JSON object
E/FxAccounts(19418):    at org.mozilla.gecko.sync.ExtendedJSONObject.<init>(ExtendedJSONObject.java:217)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.MozResponse.jsonObjectBody(MozResponse.java:110)
E/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:152)
E/FxAccounts(19418):    ... 14 more
D/FxAccounts(19418): firefox :: AndroidFxAccount :: Returning cached account bundle.
D/FxAccounts(19418): firefox :: AndroidFxAccount :: Returning cached account bundle.
D/FxAccounts(19418): firefox :: AndroidFxAccount :: Account is in state Married
I/FxAccounts(19418): firefox :: AndroidFxAccount :: Moving account named like XXXXXXX@XXXXXX.XXX.XXXXXXX.XX to state Cohabiting
D/FxAccounts(19418): firefox :: AndroidFxAccount :: Returning cached account bundle.
I/FxAccounts(19418): firefox :: LoginStateMachineDelegate :: Fetching profile avatar information.
W/FxAccounts(19418): firefox :: FxAccountSyncAdapter :: Global session failed.
E/FxAccounts(19418): firefox :: FxAccountSyncAdapter :: Got exception syncing.
E/FxAccounts(19418): org.mozilla.gecko.tokenserver.TokenServerException$TokenServerMalformedResponseException: org.mozilla.gecko.sync.NonObjectJSONException: value must be a JSON object
E/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:155)
E/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient$TokenFetchResourceDelegate.handleHttpResponse(TokenServerClient.java:280)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:309)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:340)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.BaseResource.get(BaseResource.java:346)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter.syncWithAssertion$1a55e242(FxAccountSyncAdapter.java:373)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter$3.handleMarried(FxAccountSyncAdapter.java:542)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.authenticator.FxADefaultLoginStateMachineDelegate.handleFinal(FxADefaultLoginStateMachineDelegate.java:81)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine$ExecuteDelegate.handleTransition(FxAccountLoginStateMachine.java:64)
E/FxAccounts(19418):    at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:28)
E/FxAccounts(19418):    at org.mozilla.gecko.background.fxa.FxAccountClient10$10.handleSuccess$2637ceed(FxAccountClient10.java:770)
E/FxAccounts(19418):    at org.mozilla.gecko.background.fxa.FxAccountClient10$ResourceDelegate$2.run(FxAccountClient10.java:291)
E/FxAccounts(19418):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/FxAccounts(19418):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/FxAccounts(19418):    at java.lang.Thread.run(Thread.java:818)
E/FxAccounts(19418): Caused by: org.mozilla.gecko.sync.NonObjectJSONException: value must be a JSON object
E/FxAccounts(19418):    at org.mozilla.gecko.sync.ExtendedJSONObject.<init>(ExtendedJSONObject.java:217)
E/FxAccounts(19418):    at org.mozilla.gecko.sync.net.MozResponse.jsonObjectBody(MozResponse.java:110)
E/FxAccounts(19418):    at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:152)
E/FxAccounts(19418):    ... 14 more
I/FxAccounts(19418): firefox :: FxAccountSyncAdapter :: Syncing done.
D/FxAccounts(19418): firefox :: BaseResource :: HTTP GET https://profile.accounts.firefox.com/v1/profile
```

The stack-trace comes from [here](https://github.com/mozilla/gecko-dev/blob/541bf4c5e1e721697affe0b8e694eafe44dcb992/mobile/android/services/src/main/java/org/mozilla/gecko/tokenserver/TokenServerClient.java#L155), where it mentions that sometimes the client does not return JSON... When the URL is accessed manually, a 404 is returned, with a single "0" as content, explaining the cause of the above stack trace. I have no idea however how/why this happens... One thought is that it might be related to #5.

Some more information that might be possibly relevant:

Nginx config
```
# SSL
server {
        listen 443 ssl default;
        listen [::]:443 ssl default;

        server_name domain.tld;

        # SSL stuff
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

        ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;

        ssl_session_tickets on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:10m;

        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
        ssl_prefer_server_ciphers on;

        location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
                proxy_read_timeout 120;
                proxy_connect_timeout 10;
                proxy_pass http://127.0.0.1:5000/;
        }
}
```

Syncserver.ini:
- Random set
- No new users allowed
- For the remainder the default configuration from https://docs.services.mozilla.com/howtos/run-sync-1.5.html

**Comment by rfk** [comment]
> GET /1.0/sync/1.5

I believe this should be `/token/1.0/sync/1.5` for a self-hosted setup, perhaps the token-server URI in our mobile device is not configured correctly?

**Comment by canihavesomecoffee** [comment]
You are totally right... I ran into some issues with the certificate (self-signed) & SNI, so I removed and added the account again... Didn't pay enough attention. A non-bug then :+1:
