### ISSUE TITLE
Make test fails with Permission Denied

### ISSUE THREAD

**Issue by jtbm37** [mozilla-services/syncserver#71]
Debian Wheezy

```
$ make test
./local/bin/flake8 ./syncserver
Traceback (most recent call last):
  File "./local/bin/flake8", line 9, in <module>
    load_entry_point('flake8==2.5.1', 'console_scripts', 'flake8')()
  File "/home/matrix/GitHub/syncserver/local/local/lib/python2.7/site-packages/flake8/main.py", line 25, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/home/matrix/GitHub/syncserver/local/local/lib/python2.7/site-packages/flake8/engine.py", line 284, in get_style_guide
    report = styleguide.init_report(reporter)
  File "/home/matrix/GitHub/syncserver/local/local/lib/python2.7/site-packages/flake8/engine.py", line 186, in init_report
    return self._styleguide.init_report(reporter)
  File "/home/matrix/GitHub/syncserver/local/local/lib/python2.7/site-packages/pep8.py", line 1827, in init_report
    self.options.report = (reporter or self.options.reporter)(self.options)
  File "/home/matrix/GitHub/syncserver/local/local/lib/python2.7/site-packages/pep8.py", line 1721, in __init__
    super(StandardReport, self).__init__(options)
  File "/home/matrix/GitHub/syncserver/local/local/lib/python2.7/site-packages/flake8/reporter.py", line 43, in __init__
    self.task_queue = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
make: *** [test] Error 1
```

**Comment by rfk** [comment]
I'm sorry, but this sounds like a problem with your local python install that I don't have any idea how to help debug.  If you edit the Makefile to remove the running of `flake8`, does the rest of the test suite pass successfully?
