### ISSUE TITLE
Unexpected verification error on updated syncserver

### ISSUE THREAD

**Issue by chepec** [mozilla-services/syncserver#95]
I recently took upon myself to overhaul my Firefox syncserver. Now it's no longer working, and I haven't been able to fix it. I've read all the docs, and can't find anything describing the error I see. So here goes.

This is the relevant part of the Apache error log:

```
[Mon Sep 04 23:35:10.271603 2017] [wsgi:error] [pid 3744] ERROR:tokenserver:Unexpected verification error
[Mon Sep 04 23:35:10.271740 2017] [wsgi:error] [pid 3744] Traceback (most recent call last):
[Mon Sep 04 23:35:10.271757 2017] [wsgi:error] [pid 3744]   File "/var/www/html/ffsync/local/lib/python2.7/site-packages/tokenserver/views.py", line 85, in valid_assertion
[Mon Sep 04 23:35:10.271795 2017] [wsgi:error] [pid 3744]     assertion = verifier.verify(assertion)
[Mon Sep 04 23:35:10.271823 2017] [wsgi:error] [pid 3744]   File "/var/www/html/ffsync/local/lib/python2.7/site-packages/tokenserver/verifiers.py", line 73, in verify
[Mon Sep 04 23:35:10.271838 2017] [wsgi:error] [pid 3744]     data = super(LocalVerifier, self).verify(assertion, audience)
[Mon Sep 04 23:35:10.271850 2017] [wsgi:error] [pid 3744]   File "/var/www/html/ffsync/local/lib/python2.7/site-packages/browserid/verifiers/local.py", line 96, in verify
[Mon Sep 04 23:35:10.271861 2017] [wsgi:error] [pid 3744]     cert = self.verify_certificate_chain(certificates, now=now)
[Mon Sep 04 23:35:10.271873 2017] [wsgi:error] [pid 3744]   File "/var/www/html/ffsync/local/lib/python2.7/site-packages/browserid/verifiers/local.py", line 135, in verify_certificate_chain
[Mon Sep 04 23:35:10.271885 2017] [wsgi:error] [pid 3744]     root_key = self.supportdocs.get_key(root_issuer)
[Mon Sep 04 23:35:10.271898 2017] [wsgi:error] [pid 3744]   File "/var/www/html/ffsync/local/lib/python2.7/site-packages/browserid/supportdoc.py", line 63, in get_key
[Mon Sep 04 23:35:10.271920 2017] [wsgi:error] [pid 3744]     supportdoc = self.get_support_document(hostname)
[Mon Sep 04 23:35:10.271948 2017] [wsgi:error] [pid 3744]   File "/var/www/html/ffsync/local/lib/python2.7/site-packages/browserid/supportdoc.py", line 58, in get_support_document
[Mon Sep 04 23:35:10.271973 2017] [wsgi:error] [pid 3744]     raise error
[Mon Sep 04 23:35:10.271995 2017] [wsgi:error] [pid 3744] ConnectionError: Failed to GET https://api.accounts.firefox.com/.well-known/browserid. Reason: ('bad handshake: SysCallError(0, None)',)
```

This is my Apache vhost config (it's the default vhost, since syncserver doe ):

```
<VirtualHost *:80>      
        ServerName ffsync.chepec.se
        ServerAdmin webmaster@chepec.se
        DocumentRoot /var/www/html/ffsync

        Redirect permanent / https://ffsync.chepec.se/

        ErrorLog  ${APACHE_LOG_DIR}/ffsync-chepec-se_error.log
        LogLevel warn   
        CustomLog ${APACHE_LOG_DIR}/ffsync-chepec-se_access.log combined
</VirtualHost>

<VirtualHost *:443>
        ServerName ffsync.chepec.se
        ServerAdmin webmaster@chepec.se
        DocumentRoot /var/www/html/ffsync

        SSLEngine On
        SSLCertificateKeyFile /etc/letsencrypt/live/ffsync.chepec.se/privkey.pem
        SSLCertificateFile /etc/letsencrypt/live/ffsync.chepec.se/cert.pem
        SSLCACertificateFile /etc/letsencrypt/live/ffsync.chepec.se/chain.pem

        <Directory /var/www/html/ffsync>
                Require all granted
        </Directory>
        
        WSGIProcessGroup sync
        WSGIDaemonProcess sync user=www-data group=www-data processes=2 threads=25 python-path=/var/www/html/ffsync/local/lib/python2.7/site-packages/
        WSGIPassAuthorization On
        WSGIScriptAlias / /var/www/html/ffsync/syncserver.wsgi

        ErrorLog  ${APACHE_LOG_DIR}/ffsync-chepec-se_error.log
        LogLevel warn   
        CustomLog ${APACHE_LOG_DIR}/ffsync-chepec-se_access.log combined
</VirtualHost>
```

As for the overhaul, I updated syncserver by pulling the latest from this git repo:

```
cd /var/www/html/ffsync
git stash
git pull 
git stash pop
make build
```

I am not sure if the `make test` output means it is OK or not, so here it is:

```
$ make test
./local/bin/flake8 ./syncserver
./local/bin/nosetests -s syncstorage.tests
............................................................................S.......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...................................................S....................................................................SSSSSSSSSSSSSSSSS.SS...................
----------------------------------------------------------------------
Ran 429 tests in 138.630s

OK (SKIP=207)
# Tokenserver tests currently broken due to incorrect file paths
# ./local/bin/nosetests -s tokenserver.tests
# Test against a running server.
./local/bin/gunicorn --paste syncserver/tests.ini 2> /dev/null & SERVER_PID=$!; \
sleep 2; \
./local/bin/python -m syncstorage.tests.functional.test_storage \
	--use-token-server http://localhost:5000/token/1.0/sync/1.5; \
kill $SERVER_PID
s...s.s.........................s..................s...s..s
----------------------------------------------------------------------
Ran 59 tests in 25.398s

OK (skipped=7)
```

And the contents of `syncserver.ini` (sensitive parts redacted):

```
[server:main]
use = egg:gunicorn
host = 0.0.0.0
port = 5000
workers = 2
timeout = 60
syslog = true
syslog_prefix = ffsync
syslog_facility = daemon

[app:main]
use = egg:syncserver

[syncserver]
public_url = https://ffsync.chepec.se/

sqluri = pymysql://ffsync:<password>@localhost/ffsync

secret = <secret>

allow_new_users = true

force_wsgi_environ = false

#[browserid]
#backend = tokenserver.verifiers.LocalVerifier
#audiences = https://ffsync.chepec.se
```

And yes, syncing does not work.

I have updated the system (Debian 8.9) with the latest patches, and also wiped the syncserver MySQL database. I have tried enabling the `[browserid]` tokens above (I thought the error might be related) but that had no effect. I've also made sure that all files in `/var/www/html/ffsync` (recursively) are owned by `www-data`.

And I could `curl https://api.accounts.firefox.com/.well-known/browserid` from the server in question without issue. Any thoughts?

**Comment by rfk** [comment]
@chepec thanks for the very detailed report!  Unfortunately in my experience this:

```
Reason: ('bad handshake: SysCallError(0, None)',
```

Usually indicates some low-level problem with the python install that you're using.  Some things that might help:

* Doing a full rebuild by `rm -rf ./local && make build`
* Installing pyopenssl with `./local/bin/pip install pyopenssl`
* Trying to ensure that mod_wsgi is using the correct setup for your virtualenv, e.g. by following advice in http://flask.pocoo.org/docs/0.12/deploying/mod_wsgi/#working-with-virtual-environments

Googling for that error message reveals a couple of other things that have worked for other people, but the above seem the most likely to help for you case.  I hope one of them does!

**Comment by chepec** [comment]
Installing pyopenssl did the trick! It actually installed what looks like other crypto-related packages too:

```
$ ./local/bin/pip install pyopenssl
Collecting pyopenssl
  Downloading pyOpenSSL-17.2.0-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 4.5MB/s 
Collecting cryptography>=1.9 (from pyopenssl)
  Downloading cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 566kB/s 
Requirement already satisfied: six>=1.5.2 in ./local/lib/python2.7/site-packages (from pyopenssl)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyopenssl)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 10.4MB/s 
Collecting ipaddress (from cryptography>=1.9->pyopenssl)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting cffi>=1.7 (from cryptography>=1.9->pyopenssl)
  Downloading cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl (392kB)
    100% |████████████████████████████████| 399kB 3.2MB/s 
Collecting idna>=2.1 (from cryptography>=1.9->pyopenssl)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 10.1MB/s 
Requirement already satisfied: enum34 in ./local/lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl)
Collecting pycparser (from cffi>=1.7->cryptography>=1.9->pyopenssl)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 5.0MB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built pycparser
Installing collected packages: asn1crypto, ipaddress, pycparser, cffi, idna, cryptography, pyopenssl
Successfully installed asn1crypto-0.22.0 cffi-1.10.0 cryptography-2.0.3 idna-2.6 ipaddress-1.0.18 pycparser-2.18 pyopenssl-17.2.0
```

With the rest of the configuration as post previously, I no longer see any error messages, and the access log is filling up nicely with GETs, PUTs and POSTs :-)

Thank you for all the suggestions! Much appreciated.
